/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/apartment.glb -o components/ApartmentModel.tsx --types 
Author: Katydid (https://sketchfab.com/Katydid.)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/small-apartment-morning-version-7f0add3fe6f5404c8c7dc2deb08781a8
Title: Small Apartment (morning version)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Material2: THREE.Mesh
    Material2_1: THREE.Mesh
    Material3: THREE.Mesh
    Material3_1: THREE.Mesh
    Material3_2: THREE.Mesh
    Material3_3: THREE.Mesh
    Material2_2: THREE.Mesh
    Material3_4: THREE.Mesh
  }
  materials: {
    material_1: THREE.MeshStandardMaterial
    auto: THREE.MeshStandardMaterial
    auto_2: THREE.MeshStandardMaterial
    auto_3: THREE.MeshStandardMaterial
    auto_4: THREE.MeshStandardMaterial
    auto_5: THREE.MeshStandardMaterial
    auto_6: THREE.MeshStandardMaterial
    auto_7: THREE.MeshStandardMaterial
    edge_color646464255: THREE.LineBasicMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/apartment.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Material2.geometry} material={materials.material_1} />
        <mesh geometry={nodes.Material2_1.geometry} material={materials.auto} />
        <mesh geometry={nodes.Material3.geometry} material={materials.auto_2} />
        <mesh geometry={nodes.Material3_1.geometry} material={materials.auto_3} />
        <mesh geometry={nodes.Material3_2.geometry} material={materials.auto_4} />
        <mesh geometry={nodes.Material3_3.geometry} material={materials.auto_5} />
        <mesh geometry={nodes.Material2_2.geometry} material={materials.auto_6} />
        <mesh geometry={nodes.Material3_4.geometry} material={materials.auto_7} />
        <lineSegments geometry={nodes.Material2_3.geometry} material={materials.edge_color646464255} />
      </group>
    </group>
  )
}

useGLTF.preload('/apartment.glb')
